package usersManagement;

public enum Permission {
	ALTER_COMPANIES, ALTER_CONTRACTS, ALTER_USER_PERMISSIONS, CREATE_USER, DELETE_CONTRACTS, VIEW_CONTRACTS, VIEW_HOME, VIEW_OWN_CONTRACTS, VIEW_USERS;
}
